# Generated by Django 4.2.30 on 2026-05-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_core', '0002_alter_client_options_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=12, verbose_name='Tipo de Cambio'),
        ),
    ]
