# Generated by Django 4.2.30 on 2026-05-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_core', '0004_globalsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsetting',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=10.0, max_digits=12, verbose_name='Tipo de Cambio Global (1 USD = X Bs)'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('BOB', 'BOB')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dólares (USD)'), ('BOB', 'Bolivianos (Bs)')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
    ]
