# Generated by Django 4.2.30 on 2026-06-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_core', '0005_alter_globalsetting_exchange_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='project',
        ),
        migrations.DeleteModel(
            name='GlobalSetting',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
